version: "3.8"

services:
  app:
    image: savings-manager
    build: ./
    ports:
      - 8000:8000
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:Z
    env_file: .env
    depends_on:
      - db
      - redis
    command: ["uvicorn", "app.main:app","--host", "0.0.0.0", "--reload"]

  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

  redis:
    image: redis:7.0.7-alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  pg_data:
